In [2]:
import numpy as np
'''q.4 Create an array as :
[[1,1,1,1,1],[1,0,0,0,1],[1,0,9,0,1],[1,0,0,0,1],[1,1,1,1,1]]

note : don not use np.array direct.'''
a=np.ones((5,5),dtype=int)
#print(a)
#print(a[0],a[1],a[2],a[3],a[4])
for i in range(1,4):
    a[1][i]=0
    a[3][i]=0
    a[2][i]=0
    a[2][2]=9
print(a)

[[1 1 1 1 1]
 [1 0 0 0 1]
 [1 0 9 0 1]
 [1 0 0 0 1]
 [1 1 1 1 1]]


In [3]:
#q.5 Create a 3x3 matrix with values ranging from 0 to 8
a=np.mat([[0,1,2],[4,3,5],[6,7,8]])
a

matrix([[0, 1, 2],
        [4, 3, 5],
        [6, 7, 8]])

In [4]:
a=np.arange(0,9)
np.mat(a).reshape(3,3)

matrix([[0, 1, 2],
        [3, 4, 5],
        [6, 7, 8]])

In [6]:
#q.6 Find indices of non-zero elements from [1,2,0,0,4,0]
a=np.array([1,2,0,0,4,0])
print(a)
np.where(a>0)

[1 2 0 0 4 0]


(array([0, 1, 4], dtype=int64),)

In [7]:
#Q.7 Create a 10x10 array with random values and find the minimum and maximum values
np.random.seed(2)
a=np.random.uniform(0,200,100).reshape(10,10)
print(a)

[[ 87.19898043   5.18524637 109.93249558  87.06447852  84.07356042
   66.0669642   40.92972681 123.85419327  59.93093473  53.36545502]
 [124.22676655 105.82841886  26.91598907 102.71562425  36.88797313
  157.06702956 170.79505853  98.84736748 169.31229707  15.9290954 ]
 [101.04921802  13.05730088  85.62446552  19.30618313  25.43199434
  119.3490618   45.20240012  21.38913686  44.06124141  69.965257  ]
 [ 93.55749692  40.34864525 128.08134504  96.61396711 101.047344
   77.37853022 158.72749089 116.00083578  32.4597197  140.15046932]
 [192.91021602 100.00167223 177.90401279  68.32273053 113.42882553
   85.50919266  87.34945261 155.311837   107.1208347  190.74844539]
 [108.84163203  16.41898446  73.26848034 170.1701008   81.25500861
    5.44047318  49.4354478   13.42887415 198.77040228 194.11606268]
 [160.05167023 120.36342428 152.99197209  33.84508932  58.60464636
  104.81337506  71.32485622   9.13579305 196.63068907  88.27098387]
 [100.80008788  64.70826351  51.94895055  77.37797706 166