In [2]:
import numpy as np
#q.3
#a) Create a null vector of size 10 but the fifth value which is 1

v=np.zeros(10,dtype=int) #np.zeros(10,) comma as row and col not judged
v[4]=1
v

array([0, 0, 0, 0, 1, 0, 0, 0, 0, 0])

In [3]:
#b)Reverse a vector (first element becomes last)
v=np.arange(10)
print(v)
first=v[0]
v[0]=v[9]
v[9]=first
print("reversed:",v)

[0 1 2 3 4 5 6 7 8 9]
reversed: [9 1 2 3 4 5 6 7 8 0]


In [4]:
#c) sort it.
print("sorted:",v[-1::-1])
print(np.sort(v))

sorted: [0 8 7 6 5 4 3 2 1 9]
[0 1 2 3 4 5 6 7 8 9]
