In [1]:
#q.8 Create a random vector of size 30 and find the mean value
import numpy as np
random_vector=np.random.randint(1,100,30)
print("random vector is \n\n",random_vector)
print("the mean of this vector is :\n\n",np.mean(random_vector))


random vector is 

 [35 45 42 67 76  8 93 53 40 82 77 10  9 56 97 75 67 42 10 71 59 28 44 27
 94 48 46 51 66 82]
the mean of this vector is :

 53.333333333333336


In [2]:
#q.9 Create a 2dimensional array of size with 1 on the border and 0 inside
import numpy as np
Z = np.ones((6,6))
Z[1:-1,1:-1] = 0
print(Z)

[[1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1.]]


In [3]:
#q.10 How to add a border (filled with 0's) around an existing array?
import numpy as np
zero_arr=np.ones((6,6))
print(zero_arr)
zero_arr
zero_arr[:,0]=0
zero_arr[:,-1]=0
zero_arr[0,1:-1]=0
zero_arr[-1,1:-1]=0
print("array with border filled with zeros\n",zero_arr)

[[1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]]
array with border filled with zeros
 [[0. 0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 0.]
 [0. 0. 0. 0. 0. 0.]]


In [4]:
#q.11 Create a 5x5 matrix with values 1,2,3,4 just below the main diagonal
import numpy as np
m1=np.diag([1,2,3,4],k=-1)
print(m1)

[[0 0 0 0 0]
 [1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]]
