In [1]:
#q.12 Multiply a 5x3 matrix by a 3x2 matrix (real matrix product)
import numpy as np
k1=np.ones((5,3))
k11=np.mat(k1)
type(k11)
k2=np.ones((3,2))
k22=np.mat(k2)
k11*k22

matrix([[3., 3.],
        [3., 3.],
        [3., 3.],
        [3., 3.],
        [3., 3.]])

In [2]:
#q.13 create a 1D array, square all elements which are greater than 3
a=np.random.randint(1,15,5)
print(a)
k=np.where(a>3,a**2,a)
k

[11 12  5  6 11]


array([121, 144,  25,  36, 121])

In [4]:
#q.14 Extract the integer part of a random array of positive numbers using different methods
#hint: %, np.floor, astype, np.trunc

a=np.random.uniform(1,100,10)
np.floor(a)
a1=a.astype("int")
a1

array([64, 13, 75, 89, 59,  8, 71,  6, 87, 19])

In [5]:
#q.15 Create a 5x5 matrix with row values ranging from 0 to 4
x = np.zeros((5,5))
print("Original array:")
print(x)
print("Row values ranging from 0 to 4.")
x += np.arange(5)   # broadcasting 
print(x)


Original array:
[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]
Row values ranging from 0 to 4.
[[0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]]
