In [1]:
import numpy as np #np--shortname---np is the alice of numpy
d1=np.array([400,300,100,200])
sp1=np.array([40,50,70,60])
print(d1/sp1) #array performs element wise operation

[10.          6.          1.42857143  3.33333333]


In [2]:
import sys
l=list(range(100))
a=np.arange(100)
print(sys.getsizeof(l),"bytes is of list") #sys.getsizeof(l): size of each element in the 
print(a.itemsize)
print(a.size*a.itemsize,"bytes is of array")  #itemsize: size of each element in the array

856 bytes is of list
4
400 bytes is of array


In [3]:
import numpy as np 
arr = np.array([[[1, 2, 3], [4, 5, 6]] , [[7, 8, 9], [10, 11, 12]]])
print(np.shape(arr))
print(arr[1][0])
print(arr[1][:,1:3]) #8,9,11,12

(2, 2, 3)
[7 8 9]
[[ 8  9]
 [11 12]]
